# Generated by Django 5.2.13 on 2026-05-04 14:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("produto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEstoqueModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_estoque",
                        to="produto.produtomodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Estoque",
                "verbose_name_plural": "Itens de Estoque",
                "db_table": "item_estoque",
            },
        ),
    ]
